services:
  - type: web
    name: ardoff-offroad-club
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: "*.pdf"
        name: Content-Type
        value: application/pdf
      - path: "*.pdf"
        name: Content-Disposition
        value: inline 